# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: XBSLink-NG
version: "2026.2.3"
slug: xbslink-ng
description: P2P bridge for Xbox System Link over the internet
url: "https://github.com/jchadwick/home-assistant-addons/tree/main/xbslink-ng"
image: "ghcr.io/jchadwick/{arch}-addon-xbslink-ng"
arch:
  - amd64
  - aarch64
init: false
host_network: true
privileged:
  - NET_RAW
  - NET_ADMIN
services:
  - mqtt:want

options:
  mode: "listen"
  interface: "enp1s0"
  key: ""
  peer_address: ""
  xbox_mac: ""
  log_level: "info"
  stats_interval: 5
  port: 31415
  mqtt_enabled: false

schema:
  mode: "list(listen|connect)"
  interface: "str"
  xbox_mac: "str?"
  key: "str?"
  log_level: "list(error|warn|info|debug|trace)"
  stats_interval: "int(0,3600)"
  port: "port?"
  peer_address: "str?"
  mqtt_enabled: "bool?"
